version: '2'
services:
  dns:
    restart: always
    image: alpine:latest
    entrypoint: ["ash", "/entrypoint.sh"]
    command: -q
    container_name: dnsmasq
    volumes:
      - /srv/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - /srv/entrypoint/dnsmasq.sh:/entrypoint.sh:ro
    ports:
      - "53:53"
      - "53:53/udp"
      - "5380:8080"
    cap_add:
      - NET_ADMIN

  revproxy:
    restart: no
    image: alpine:3.4
    entrypoint: ["ash", "/entrypoint.sh"]
    container_name: nginx
    volumes:
      - /srv/crt:/crt:ro
      - /srv/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - /srv/entrypoint/nginx.sh:/entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
      - "5381:8080"
    cap_add:
      - NET_ADMIN
